API/urls.py
from django.urls import path, include
from rest_framework import routers
from API import views

router = routers.DefaultRouter()
router.register(r'SCotizacion', views.SCotizacionViewSet)
router.register(r'OrdenCompra', views.Orden_De_Compra_ViewSet)

urlpatterns = [
    path('', include(router.urls)),
    
]

Api_SI/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls
from API.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',inicio, name='inicio'),
    path('api/', include('API.urls')),
    path('docs/', include_docs_urls(title='Api documentacion')),
    path('Scotizacion/', Scotizacion, name='Scotizacion'),
    path('Scompra/', Scompra, name='Scompra'),
    path('solicitud_exito/', solicitud_exito, name='solicitud_exito'),
    path('acerca_erp/', acerca_erp, name='acerca_erp'),
    path('soporte/', soporte, name='soporte'),
    path('scompra/<int:pk>/actualizar/', actualizar_scompra, name='actualizar_scompra'),
    path('scompra/<int:pk>/eliminar/', eliminar_scompra, name='eliminar_scompra'),
    path('scotizacion/<int:pk>/actualizar/', actualizar_scotizacion, name='actualizar_scotizacion'),
    path('scotizacion/<int:pk>/eliminar/', eliminar_scotizacion, name='eliminar_scotizacion'),
]

API/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

class SolicitudCotizacion(models.Model):
    nombre_cliente = models.CharField(max_length=100)
    correo_cliente = models.EmailField()
    telefono_cliente = models.CharField(max_length=20)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)
    fecha_limite = models.DateTimeField()
    producto_solicitud = models.CharField(max_length=100)
    cantidad_solicitud = models.PositiveIntegerField()
    descripcion_cotizacion = models.TextField()
    estado_solicitud = models.CharField(max_length=50, default='En espera')
    estadoActividad = models.PositiveIntegerField(default=1)

    def clean(self):
        # Verifica que fecha_limite sea posterior a la fecha actual
        if self.fecha_limite <= timezone.now():
            raise ValidationError("La fecha límite debe ser posterior a la fecha actual.")

    # Método opcional: si quieres que siempre se valide antes de guardar
    def save(self, *args, **kwargs):
        self.clean()  # Ejecuta la validación antes de guardar
        super().save(*args, **kwargs)

        
class Orden_De_Compra(models.Model):
    solicitud = models.ForeignKey(SolicitudCotizacion, on_delete=models.CASCADE, related_name='ordenes_de_compra')
    proveedor = models.CharField(max_length=100)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_aprobada = models.PositiveIntegerField(default=1)  # Cantidad que se ha decidido comprar
    tiempo_entrega = models.DateTimeField()  # Tiempo de entrega en calendario
    condiciones = models.TextField()
    total = models.DecimalField(max_digits=10, decimal_places=2, editable=False)  # Total calculado
    estado = models.CharField(max_length=50, default='Por revisar')
    fecha_cotizacion = models.DateTimeField(auto_now_add=True)

    def clean(self):
        # Verifica que fecha_limite sea posterior a la fecha actual
        if self.tiempo_entrega < timezone.now():
            raise ValidationError("La fecha límite de entrega debe ser posterior o igual a la fecha actual.")

    def save(self, *args, **kwargs):
        self.clean()  # Ejecuta la validación antes de guardar
        # Calcular el total antes de guardar
        self.total = self.precio_unitario * self.cantidad_aprobada
        super().save(*args, **kwargs)

API/forms.py
from django import forms
from .models import Orden_De_Compra, SolicitudCotizacion
from django.core.exceptions import ValidationError
from django.utils import timezone

class SolicitudCotizacionForm(forms.ModelForm):
    class Meta:
        model = SolicitudCotizacion
        fields = [
            'nombre_cliente',
            'correo_cliente',
            'telefono_cliente',
            'fecha_limite',
            'producto_solicitud',
            'cantidad_solicitud',
            'descripcion_cotizacion',
        ]
        widgets = {
            'fecha_limite': forms.DateTimeInput(attrs={'type': 'datetime-local'}),  # Formato adecuado para la fecha
        }

    def clean_fecha_limite(self):
        fecha_limite = self.cleaned_data['fecha_limite']
        if fecha_limite <= timezone.now():
            raise ValidationError("La fecha límite debe ser posterior a la fecha actual.")
        return fecha_limite

class OrdenDeCompraForm(forms.ModelForm):
    class Meta:
        model = Orden_De_Compra
        fields = [
            'solicitud',
            'proveedor',
            'precio_unitario',
            'cantidad_aprobada',
            'tiempo_entrega',
            'condiciones',
            'estado',
        ]
        widgets = {
            'tiempo_entrega': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'condiciones': forms.Textarea(attrs={'rows': 4}),
        }

    def clean_tiempo_entrega(self):
        tiempo_entrega = self.cleaned_data['tiempo_entrega']
        if tiempo_entrega < timezone.now():
            raise ValidationError("La fecha límite de entrega debe ser posterior o igual a la fecha actual.")
        return tiempo_entrega

API/views.py
from django.http import HttpResponse
import requests
from rest_framework import viewsets

from API.forms import OrdenDeCompraForm, SolicitudCotizacionForm
from .serializer import *
from .models import *
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
# Create your views here.

class SCotizacionViewSet(viewsets.ModelViewSet):
    queryset = SolicitudCotizacion.objects.all()
    serializer_class = SCotizacionSerializer

class Orden_De_Compra_ViewSet(viewsets.ModelViewSet):
    queryset = Orden_De_Compra.objects.all()
    serializer_class = Orden_De_Compra_Serializer

# Nueva función para renderizar un HTML

from datetime import datetime
from django.utils import timezone

def Scompra(request):
    # Consume las APIs externas
    response = requests.get('https://sistemas-integrados-inventario-production.up.railway.app/api/proveedores/')

    if response.status_code == 200:
        data = response.json()

        # Maneja la solicitud POST (envío del formulario)
        if request.method == 'POST':
            form = OrdenDeCompraForm(request.POST)
            if form.is_valid():
                form.save()  # Guarda la solicitud si es válida
                return solicitud_exito(request)  # Llama a la función y devuelve su resultado
            else:
                return JsonResponse({
                    'status': 'error',
                    'message': 'Hubo un error al enviar el formulario.'
                })

        # Maneja la solicitud GET (muestra el formulario y los datos de las APIs)
        else:
            form = OrdenDeCompraForm()
            context = {
                'proveedores': data,
                'solicitudes': SolicitudCotizacion.objects.all(),  # Obtén las solicitudes relacionadas
            }
            return render(request, 'Scompras.html', context)
    else:
        # Maneja errores en caso de que alguna de las APIs falle
        return render(request, 'error.html', {'error': 'Error al consumir las APIs'})
    

def actualizar_scompra(request, pk):
    # Obtener la orden de compra mediante el ID (pk)
    orden_compra = get_object_or_404(Orden_De_Compra, pk=pk)

    # Consumir las API de proveedores
    response = requests.get('https://sistemas-integrados-inventario-production.up.railway.app/api/proveedores/')
    
    if response.status_code == 200:
        data = response.json()

        # Procesar el formulario de actualización
        if request.method == 'POST':
            form = OrdenDeCompraForm(request.POST, instance=orden_compra)
            if form.is_valid():
                form.save()  # Guarda los cambios
                return redirect('solicitud_exito')  # Redirige a la página de éxito
            else:
                return JsonResponse({
                    'status': 'error',
                    'message': 'Hubo un error al actualizar la solicitud.'
                })

        else:
            form = OrdenDeCompraForm(instance=orden_compra)
            context = {
                'form': form,
                'proveedores': data,  # Pasamos los proveedores al contexto
                'solicitudes': SolicitudCotizacion.objects.all()  # Pasamos las solicitudes al contexto
            }
            return render(request, 'Scompras.html', context)
    else:
        return render(request, 'error.html', {'error': 'Error al consumir las APIs'})

def eliminar_scompra(request, pk):
    orden_compra = get_object_or_404(Orden_De_Compra, pk=pk)
    orden_compra.delete()  # Elimina la orden de compra
    return redirect('solicitud_exito')  # Redirige a la página de éxito

def ObtenerCotizacion(request):
    cotizaciones = SolicitudCotizacion.objects.all()
    return render(request, 'Solicitud_exito.html', {'cotizaciones': cotizaciones})

def Scotizacion(request):
    # Consume las APIs externas
    response = requests.get('https://contactomodulo-production.up.railway.app/api/clientes')
    response2 = requests.get('https://sistemas-integrados-inventario-production.up.railway.app/api/productos/')

    if response.status_code == 200 and response2.status_code == 200:
        data = response.json()
        data2 = response2.json()

        # Maneja la solicitud POST (envío del formulario)
        if request.method == 'POST':
            form = SolicitudCotizacionForm(request.POST)
            if form.is_valid():
                form.save()  # Guarda la solicitud si es válida
                return solicitud_exito(request)  # Llama a la función y devuelve su resultado
            else:
                return JsonResponse({
                    'status': 'error',
                    'message': 'Hubo un error al enviar el formulario.'
                })

        # Maneja la solicitud GET (muestra el formulario y los datos de las APIs)
        else:
            form = SolicitudCotizacionForm()
            context = {
                'form': form,
                'clientes': data,
                'productos': data2
            }
            return render(request, 'Scotizacion.html', context)

    else:
        # Maneja errores en caso de que alguna de las APIs falle
        return render(request, 'error.html', {'error': 'Error al consumir las APIs'})

def actualizar_scotizacion(request, pk):
    # Obtener la cotización por pk
    cotizacion = get_object_or_404(SolicitudCotizacion, pk=pk)

    # Consumir las APIs
    response = requests.get('https://contactomodulo-production.up.railway.app/api/clientes')
    response2 = requests.get('https://sistemas-integrados-inventario-production.up.railway.app/api/productos/')

    if response.status_code == 200 and response2.status_code == 200:
        data = response.json()
        data2 = response2.json()

        # Procesar el formulario
        if request.method == 'POST':
            form = SolicitudCotizacionForm(request.POST, instance=cotizacion)
            if form.is_valid():
                form.save()
                return redirect('solicitud_exito')  # Redirige a una página de éxito
        else:
            form = SolicitudCotizacionForm(instance=cotizacion)

        # Pasar las APIs al contexto
        return render(request, 'Scotizacion.html', {
            'form': form,
            'clientes': data,
            'productos': data2
        })
    else:
        return render(request, 'error.html', {'error': 'Error al consumir las APIs'})


def eliminar_scotizacion(request, pk):
    cotizacion = get_object_or_404(SolicitudCotizacion, pk=pk)
    cotizacion.delete()  # Elimina la solicitud de cotización
    return redirect('solicitud_exito')  # Redirige a la página de éxito

def solicitud_exito(request):
    # Recuperar todas las solicitudes de cotización y órdenes de compra
    cotizaciones = SolicitudCotizacion.objects.all()
    compras = Orden_De_Compra.objects.all()

    context = {
        'cotizaciones': cotizaciones,
        'compras': compras,
    }
    return render(request, 'solicitud_exito.html', context)

def index(request):
    return render(request, 'index.html')

def acerca_erp(request):
    return render(request, 'Acerca_ERP.html')

def soporte(request):
    return render(request, 'Soporte.html')

def inicio(request):
    return render(request, 'inicio.html')

API/templates/Acerca_ERP.html
{% extends "index.html" %}

{% block title %}Acerca del ERP - Mi Proyecto ERP{% endblock %}

{% block content %}
<div class="container flex-grow-1 text-center mt-5">
    <h1 class="display-4 text-primary">¿Qué es nuestro ERP de Compras?</h1>
    <p class="lead text-muted mb-4">Nuestro ERP de Compras está diseñado para ayudar a las empresas a gestionar sus compras de manera eficiente, centralizando todos los procesos relacionados con la cotización, compra, y administración de proveedores.</p>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h5 class="card-title">Funcionalidades Principales</h5>
                    <ul class="list-unstyled">
                        <li><strong>Cotizaciones:</strong> Genera y gestiona cotizaciones con proveedores fácilmente.</li>
                        <li><strong>Órdenes de Compra:</strong> Aprobación y seguimiento de órdenes de compra.</li>
                        <li><strong>Historial de Compras:</strong> Mantén un registro detallado de todas las compras realizadas.</li>
                        <li><strong>Informes:</strong> Genera informes personalizados sobre el estado de tus compras y cotizaciones.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-5">
        <h4>¿Cómo puede ayudarte?</h4>
        <p class="text-muted">Este ERP está pensado para facilitar la toma de decisiones al centralizar toda la información de compras, proveedores y órdenes en un solo lugar, brindándote visibilidad en tiempo real sobre el estado de tu negocio.</p>
    </div>
</div>
{% endblock %}

API/templates/Scompras.html
{% extends "index.html" %}

{% block title %}Soporte - Mi Proyecto ERP{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Orden de Compra</title>
    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
    <style>


      .form-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        padding: 40px;
        max-width: 800px;
        margin: 50px auto;
      }

      .form-container h2 {
        font-size: 28px;
        margin-bottom: 20px;
        text-align: center;
        color: #343a40;
      }

      .form-control {
        border-radius: 8px;
        padding: 10px;
        font-size: 16px;
      }

      .form-control:focus {
        border-color: #6c757d;
        box-shadow: 0 0 8px rgba(108, 117, 125, 0.5);
      }

      .btn-custom {
        background-color: #009b8e;
        color: #fff;
        border-radius: 8px;
        padding: 12px 20px;
        font-size: 16px;
        width: auto;
      }

      .btn-custom:hover {
        background-color: #00b386;
      }

      .section-header {
        font-size: 20px;
        color: #495057;
        margin-bottom: 20px;
        font-weight: bold;
        border-bottom: 1px solid #000000;
        padding-bottom: 10px;
      }

      .form-label {
        font-weight: 600;
        color: #495057;
      }

      .mb-5 {
        margin-bottom: 40px !important;
      }

      .btn-container {
        text-align: center;
      }
    </style>
  </head>

  <body>
    <div class="container">
      <div class="form-container">
        <h2>Registrar Orden de Compra</h2>

        <form method="post">
            {% csrf_token %}
        
            <!-- Solicitud Relacionada -->
            <div class="form-section mb-5">
                <div class="section-header">Solicitud Relacionada</div>
                <div class="mb-3">
                    <label for="solicitud" class="form-label">Solicitud Relacionada:</label>
                    <select id="solicitud" name="solicitud" class="form-select" required>
                        <option value="" disabled selected>Selecciona una solicitud</option>
                        {% for solicitud in solicitudes %}
                            <option value="{{ solicitud.id }}" {% if solicitud.id == form.solicitud.value %}selected{% endif %}>
                                {{ solicitud.nombre_cliente }} - {{ solicitud.producto_solicitud }}
                            </option>
                        {% empty %}
                            <option value="" disabled>No hay solicitudes disponibles</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        
            <!-- Proveedor -->
            <div class="form-section mb-5">
                <div class="section-header">Proveedor</div>
                <div class="mb-3">
                    <label for="proveedor" class="form-label">Proveedor:</label>
                    <select id="proveedor" name="proveedor" class="form-select" required>
                        <option value="" disabled selected>Selecciona un proveedor</option>
                        {% for proveedor in proveedores %}
                            <option value="{{ proveedor.nombre }}" {% if proveedor.nombre == form.proveedor.value %}selected{% endif %}>
                                {{ proveedor.nombre }}
                            </option>
                        {% empty %}
                            <option value="" disabled>No hay proveedores disponibles</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        
            <!-- Precio Unitario -->
            <div class="form-section mb-5">
                <div class="section-header">Detalles de la Orden</div>
                <div class="mb-3">
                    <label for="precio_unitario" class="form-label">Precio Unitario:</label>
                    <input type="number" name="precio_unitario" id="precio_unitario" class="form-control" step="0.01" value="{{ form.precio_unitario.value|default:'' }}" required />
                </div>
        
                <div class="mb-3">
                    <label for="cantidad_aprobada" class="form-label">Cantidad Aprobada:</label>
                    <input type="number" name="cantidad_aprobada" id="cantidad_aprobada" class="form-control" min="1" value="{{ form.cantidad_aprobada.value|default:'' }}" required />
                </div>
        
                <div class="mb-3">
                    <label for="tiempo_entrega" class="form-label">Tiempo de Entrega:</label>
                    <input type="datetime-local" name="tiempo_entrega" id="tiempo_entrega" class="form-control" value="{{ form.tiempo_entrega.value|default:'' }}" required />
                </div>
        
                <div class="mb-3">
                    <label for="condiciones" class="form-label">Condiciones:</label>
                    <textarea name="condiciones" id="condiciones" class="form-control" rows="4">{{ form.condiciones.value|default:'' }}</textarea>
                </div>
        
                <div class="mb-3">
                    <label for="estado" class="form-label">Estado:</label>
                    <select name="estado" id="estado" class="form-select" required>
                        <option value="Por revisar" {% if form.estado.value == 'Por revisar' %}selected{% endif %}>Por revisar</option>
                        <option value="Aprobada" {% if form.estado.value == 'Aprobada' %}selected{% endif %}>Aprobada</option>
                        <option value="Rechazada" {% if form.estado.value == 'Rechazada' %}selected{% endif %}>Rechazada</option>
                    </select>
                </div>
            </div>
        
            <div class="btn-container">
                <button type="submit" class="btn btn-custom">Actualizar Orden</button>
            </div>
        </form>
        
      </div>
    </div>

    <!-- Bootstrap 5 JS -->
  </body>
</html>
{% endblock %}

API/templates/Scotizacion.html
{% extends "index.html" %}

{% block title %}Soporte - Mi Proyecto ERP{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Solicitud de Cotización</title>
  <!-- Bootstrap 5 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
  <style>

    .form-container {
      background-color: #ffffff;
      border-radius: 10px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
      padding: 40px;
      max-width: 800px;
      margin: 50px auto;
    }

    .form-container h2 {
      font-size: 28px;
      margin-bottom: 20px;
      text-align: center;
      color: #343a40;
    }

    .form-control {
      border-radius: 8px;
      padding: 10px;
      font-size: 16px;
    }

    .form-control:focus {
      border-color: #6c757d;
      box-shadow: 0 0 8px rgba(108, 117, 125, 0.5);
    }

    .btn-custom {
      background-color: #009b8e;
      color: #fff;
      border-radius: 8px;
      padding: 12px 20px;
      font-size: 16px;
      width: auto;
    }

    .btn-custom:hover {
      background-color: #00b386;
    }

    .section-header {
      font-size: 20px;
      color: #495057;
      margin-bottom: 20px;
      font-weight: bold;
      border-bottom: 1px solid #000000;
      padding-bottom: 10px;
    }

    .form-label {
      font-weight: 600;
      color: #495057;
    }

    .mb-5 {
      margin-bottom: 40px !important;
    }

    .btn-container {
      text-align: center;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="form-container">
      <h2>Solicitud de Cotización - Módulo de Compras</h2>

      <form method="post" id="solicitud-form">
        {% csrf_token %}
        <!-- Información del Cliente -->
        <div class="form-section mb-5">
            <div class="section-header">Información del Cliente</div>
            <div class="mb-3">
                <label for="nombre_cliente" class="form-label">
                    {% if form.nombre_cliente.value %}
                        Nombre del Cliente
                    {% else %}
                        <!-- Deja el label vacío si no hay valor -->
                    {% endif %}
                </label>
                <select id="nombre_cliente" name="nombre_cliente" class="form-select" required>
                    <option value="" disabled selected>Selecciona un cliente</option>
                    {% for cliente in clientes %}
                        <option value="{{ cliente.nombres }} {{ cliente.apellidos }}" data-correo="{{ cliente.correo }}" data-telefono="{{ cliente.telefono }}"
                        {% if cliente.nombres == form.nombre_cliente.initial %} selected {% endif %}>
                            {{ cliente.nombres }} {{ cliente.apellidos }}
                        </option>
                    {% empty %}
                        <option value="" disabled>No hay clientes disponibles</option>
                    {% endfor %}
                </select>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="id_correo_cliente" class="form-label">Correo Cliente:</label>
                        <input type="email" name="correo_cliente" class="form-control" id="id_correo_cliente" value="{{ form.correo_cliente.value|default:'' }}" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="id_telefono_cliente" class="form-label">Teléfono Cliente:</label>
                        <input type="text" name="telefono_cliente" class="form-control" id="id_telefono_cliente" value="{{ form.telefono_cliente.value|default:'' }}" />
                    </div>
                </div>
            </div>
        </div>
    
        <!-- Información de la Solicitud -->
        <div class="form-section mb-5">
            <div class="section-header">Detalles de la Solicitud</div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="producto_solicitud" class="form-label">
                            {% if form.producto_solicitud.value %}
                                Producto Solicitud
                            {% else %}
                                <!-- Deja el label vacío si no hay valor -->
                            {% endif %}
                        </label>
                        <select id="producto_solicitud" name="producto_solicitud" class="form-select" required>
                            <option value="" disabled selected>Selecciona un producto</option>
                            {% for producto in productos %}
                                <option value="{{ producto.nombre }}" {% if producto.nombre == form.producto_solicitud.initial %}selected{% endif %}>
                                    {{ producto.nombre }}
                                </option>
                            {% empty %}
                                <option value="" disabled>No hay productos disponibles</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="id_cantidad_solicitud" class="form-label">Cantidad Solicitud:</label>
                        <input type="number" name="cantidad_solicitud" class="form-control" id="id_cantidad_solicitud" value="{{ form.cantidad_solicitud.value|default:'' }}" />
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="id_descripcion_cotizacion" class="form-label">Descripción Cotización:</label>
                <textarea name="descripcion_cotizacion" class="form-control" id="id_descripcion_cotizacion">{{ form.descripcion_cotizacion.value|default:'' }}</textarea>
            </div>
            <div class="mb-3">
                <label for="id_fecha_limite" class="form-label">Fecha Límite:</label>
                <input type="datetime-local" name="fecha_limite" class="form-control" id="id_fecha_limite" value="{{ form.fecha_limite.value|default:'' }}" />
            </div>
        </div>
    
        <div class="btn-container">
            <button type="submit" class="btn btn-custom">
                {% if form.instance.pk %}
                    Actualizar Solicitud
                {% else %}
                    Guardar nueva cotización
                {% endif %}
            </button>
        </div>
    </form>
    

    </div>
  </div>

  <!-- Bootstrap 5 JS -->
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      // Añadir un evento 'change' al select de cliente
      document.getElementById('nombre_cliente').addEventListener('change', function () {
        // Obtener la opción seleccionada
        var selectedOption = this.options[this.selectedIndex]

        // Obtener los valores de los atributos 'data-correo' y 'data-telefono'
        var correo = selectedOption.getAttribute('data-correo')
        var telefono = selectedOption.getAttribute('data-telefono')

        // Verificar si se han obtenido los valores
        if (correo) {
          document.getElementById('id_correo_cliente').value = correo // Asignar correo al campo
        }
        if (telefono) {
          document.getElementById('id_telefono_cliente').value = telefono // Asignar teléfono al campo
        }
      })
    })
  </script>
</body>

</html>
{% endblock %}

API/templates/Soporte.html
{% extends "index.html" %}

{% block title %}Soporte - Mi Proyecto ERP{% endblock %}

{% block content %}
<div class="container flex-grow-1 text-center mt-5">
    <h1 class="display-4 text-primary">Soporte Técnico</h1>
    <p class="lead text-muted text-center mb-4">Si necesitas ayuda o tienes alguna duda sobre cómo utilizar nuestro ERP, aquí encontrarás todo lo que necesitas saber.</p>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h5 class="card-title">¿Necesitas ayuda?</h5>
                    <p class="card-text">Nuestro equipo de soporte está disponible para responder cualquier pregunta y brindarte asistencia técnica. Puedes ponerte en contacto con nosotros de las siguientes maneras:</p>
                    <ul class="list-unstyled">
                        <li><strong>Correo electrónico:</strong> soporte@miempresa.com</li>
                        <li><strong>Teléfono:</strong> +34 123 456 789</li>
                        <li><strong>Formulario en línea:</strong> Rellena el formulario en nuestra página web y nos pondremos en contacto contigo.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-4 text-center">
        <p class="text-muted">Si prefieres, también puedes consultar nuestra <a href="/manual" class="text-info">Guía de usuario</a> para aprender más sobre cómo usar el ERP.</p>
    </div>
</div>
{% endblock %}

API/templates/inicio.html
{% extends "index.html" %}

{% block title %}Inicio - Mi Proyecto ERP{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="display-4 text-primary">Bienvenido a tu ERP de Compras</h1>
    <p class="lead text-muted mb-5">Gestiona tus cotizaciones y órdenes de compra de manera eficiente y fácil.</p>
</div>
<div class="d-flex flex-column align-items-center">
    <div class="card w-75 mb-4 shadow-lg" id="cardCotizacion">
        <div class="card-body text-center">
            <h5 class="card-title text-info">Cotizaciones de Compras</h5>
            <p class="card-text">Crea y gestiona tus cotizaciones de compras con facilidad y rapidez.</p>
            <a href="/Scotizacion/" class="btn btn-info btn-lg">Ir a Cotizaciones</a>
        </div>
    </div>

    <div class="card w-75 shadow-lg" id="cardCompra">
        <div class="card-body text-center">
            <h5 class="card-title text-success">Órdenes de Compra</h5>
            <p class="card-text">Administra y visualiza las órdenes de compra aprobadas con un solo clic.</p>
            <a href="/Scompra/" class="btn btn-success btn-lg">Ir a Órdenes de Compra</a>
        </div>
    </div>
</div>
{% endblock %}